---
title: "Silvia Sacchi - D00262683 -CA4"
subtitle: "Linear Regression Analysis of gaming habits"
author: "Silvia Sacchi"
output: 
 html_notebook:
   toc: true
   number_sections: true
   toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r}
#OPENING CSV FILE
lr <- read.csv ("C:\\Users\\Silvia\\OneDrive - Dundalk Institute of Technology\\University\\Data Analytics for Immersive Environments\\CA4\\amalgamated_game_survey_250_2022.csv")
lr
```

```{r}
#SELECTING SAMPLE OF 200 OBSERVATIONS
set.seed(12) #setting seed so that the sampling can be reproduced by anyone using this code
sample <- sample (1:nrow(lr), 200, replace = FALSE) #selecting 200 observation without replacement
sample
lr_sample <- lr [sample, ] #creating new dataset containing of the sample
lr_sample
```
```{r}
#SELECTING VARIABLES TO TEST AND ESTABLISHING HYPOTHESES
#The aim of this analysis is to test the relationship between two numerical variables via linear regression. 
#In particular, the relationship between the average monthly time spent playing (avg_monthly_hrs_gaming) and the average monthly amount spent on downloadable content (avg_monthly_expenditure_dlc) will be analysed.

#Since there is no clear indication of the unit of measurement for the monthly expenditure, it will be assumed that each amount is expressed in US dollars ($).

#What's expected is to see a higher expenditure among those who spend more time playing. In other words, the time spent playing (explanatory variable) is expected to be predictive of the amount of money a gamer will spend on downloadable content (response variable).

#The general formula for linear regression is as follows:
#ŷ = β0 + β1x
#ŷ is the estimated response value
#β0 is the intercept and represents the average value of y when x is 0. It corresponds to the point where the regression line 
#meets the y axes.
#β1 is the average change in y when x increases by 1 unit and it's called slope. In this case, it represents the average change in monthly expenditure when the average monthly time spent playing increases by 1 hour.
#x is the explanatory variable.

#Based on all this a set of hypotheses was created:
#H0: β1 = 0
#HA: β1 ≠ 0

#To rephrase it, the null hypothesis predicts a non-significant level of predictability between the time spent playing and the monthly expenditure on downloadable content, while the alternative hypothesis predicts a significant impact of monthly hours spent playing on the average monthly expenditure of the player.
```
```{r}
#CONDITIONS FOR LINEAR REGRESSION: in order to establish if linear regression is an appropriate test the following criteria must be met:
#Linearity
#Nearly normal residual
#Constant variability
#No extreme ouliers
#Such conditions will be investigated throughout this project.
```
```{r}
#SIMPLIFYING: instead of calling the column name each time a variable is analysed or tested, a new vector will be created with the values of that same column. Such new variable will then be used for all analyses.

time <- lr_sample$avg_monthly_hrs_gaming #creating new vector for monthly time spent playing
time

exp <- lr_sample$avg_monthly_expenditure_dlc #creating new vector for the monthly expenditure on downloadable content
exp
```

```{r}
#DESCRIPTIVE STATISTICS

#time
```

```{r}
mean_time <- mean (time) #finding average monthly hours spent playing
mean_time
```
```{r}
median_time <- median (time) #finding median  value for monthly hours spent playing
median_time
```
```{r}
getmode <- function(v) { # creating function to find mode
  uniqv <- unique(v)
  uniqv[which.max(tabulate(match(v, uniqv)))]
}

mode_time <- getmode (time) #finding mode value for the monthly amount of time spent playing
mode_time
```
```{r}
sd_time <- sd (time) #finding standard deviation for the monthly amount of time spent playing
sd_time
```
```{r}
var_time <- var (time) #finding variance for the monthly amount of time spent playing 
var_time
```
```{r}
iqr_time <- IQR (time) #finding IQR for the monthly amount of time spent playing
iqr_time
```
```{r}
quartiles_time <- quantile (time, prob=c(.25,.5,.75)) #finding quartiles for the monthly time spent playing
quartiles_time
```
```{r}
boxplot (time, main='Monthly amount of hours spent playing video games', ylab='Time (h) sent playing video-games monthly') #creating box plot of time spent playing

#One outlier can be visually identified in the lower part of the distribution.
#Since it's only one observation out of 200 the impact of such outlier can been considered negligible.
```
```{r}
min_time <- min (time) #finding minimum monthly amount of hours in the datset that a subject played video-games
min_time
```
```{r}
max_time <- max (time) #finding maximum monthly amount of hours in the datset that a subject played video-games
max_time
```
```{r}
range_time <- max_time - min_time #finding range for monthly time spent playing
range_time
```
```{r}
#expenditure
```
```{r}
mean_exp <- mean (exp) #finding average monthly amount spent on downloadable content
mean_exp
```
```{r}
median_exp <- median (exp) #finding median value for monthly expenditure for downloadable content
median_exp
```
```{r}
mode_exp <- getmode (exp) #finding mode value for the monthly expenditure for downloadable content
mode_exp
```
```{r}
sd_exp <- sd (exp) #finding standard deviation for the monthly amount spent on downloadable content
sd_exp
```
```{r}
var_exp <- var (exp) #finding variance for the monthly amount spent on donloadable content
var_exp
```
```{r}
iqr_exp <- IQR (exp) #finding IQR for the monthly amount spent on downloadable content
iqr_exp
```
```{r}
quartiles_exp <- quantile (exp, prob=c(.25,.5,.75)) #finding quartiles for the monthly downloadable content expenditure
quartiles_exp
```
```{r}
boxplot (exp, main='Monthly amount ($) spent on downloadable content', ylab='Amount ($) spent monthly on downloadable content') #creating box of plot monthly expenditure

#no visible outliers
```
```{r}
min_exp <- min (exp) #finding minimum monthly amount of hours spent on downloadable content
min_exp
```
```{r}
max_exp <- max (exp) #finding maximum monthly amount spent on downloadable content
max_exp
```
```{r}
range_exp <- max_exp - min_exp #finding range for monthly expenditure
range_exp
```
```{r}
#TESTING FOR NORMALITY: Linear regression requires normality, therefore normality tests will be run.

#time
```
```{r}
hist (time, col='Blue', main='Distribution of monthly time spent playing video-games', xlab='Time (h)')
#creating histogram of the distribution for the variable time

#the distribution does not seem normal. Further tests will be carried out.
```
```{r}
qqnorm (time, main='Distribution of monthly time spent playing video-games') #creating q-q- plot for the distribution of the variable time
qqline (time) #adding interpolation line

#the distribution does not appear to be normal. More testing will be performed.
```
```{r}
shapiro.test (time) #performing Shapiro-Wild test for normality

#With p < 0.001 the null hypothesis must be rejected. The data are not normal.
```
```{r}
#exp
```
```{r}
hist (exp, col='Red', main='Distribution of average monthly expenditure on downloadable content', xlab='Expenditure ($)')
#creating histogram of the distribution for the variable exp

#the distribution does not seem normal. Further tests will be carried out.
```
```{r}
qqnorm (exp, main='Distribution of monthly expenditure on dowloadable content') #creating q-q- plot for the distribution of the variable exp
qqline (exp) #adding interpolation line

#the distribution does not appear to be normal. More testing will be performed.
```
```{r}
shapiro.test (exp) #performing Shapiro-Wild test for normality

#With p < 0.001 the null hypothesis must be rejected. The data are not normal.
```
```{r}
#LINEAR REGRESSION

install.packages ("readxl") #installing readxl library
library ("readxl") #leading realxl library
```
```{r}
lmExpenditure <- lm(exp~time) #creating linear regression
summary (lmExpenditure) #viewing linear regression results

#β0 = 57.65
#β1 = -0.1
#p = 0.62 which is well above the threshold of 0.005 making this linear regression non-significant. With this parameter alone we can already establish that H0 cannot be rejected and therefore we need to assume that β1 = 0. In other words the average number of hours spent every month playing video-games doesn't predict the average monthly expenditure on downloadable content.
#Looking at the residuals, we can also see that while the median is close to 0, there is a large variability with a minimum value of -16.85 and a maximum one of 17.40, really distant from the ideal 0 that would indicate a low difference between predicted and actual values.
#R2 = 0.001 which is extremely low meaning that the model explains only 0.1% of the data variability. This is another proof of the lack of explanatory power of time over exp.
```
```{r}
install.packages ("ggplot2")
library ("ggplot2")
```
```{r}
#creating plot to visually access the linear regression model
ggplot (lr, aes (lr$avg_monthly_hrs_gaming, lr$avg_monthly_expenditure_dlc)) +
  geom_point() +
  geom_smooth (method='lm', se=FALSE, color='turquoise2') +
  theme_minimal() +
  labs(x='average monthly gaming time', y='average monthly expenditure on downloadable content', title='Linear Regression') +
  theme(plot.title = element_text(hjust=0.5, size=20, face='bold')) 

#the regression model plot further proofs the lack of a predictive relationship between the variables.
```
```{r}
install.packages ("broom")
library ("broom")
```
```{r}
augmented <- augment (lmExpenditure) #augmenting data to add fitted and residual values.
head (augmented)
```
```{r}
#creating plot to visualise the difference between predicted and actual values
ggplot (augmented, aes (time, exp)) +
  geom_point() +
  stat_smooth(method = lm, se = FALSE) +
  geom_segment(aes(xend = time, yend = .fitted), color = "red", size = 0.3)

#the visual representation of the residual allows ro easily recognise the difference between the predicted values and the actual ones. The model lacks predictability.
```
















